apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
parameters:
  basePath: /pvs
  fileSystemId: fs-00000000000000000 # TODO: Replace this with your ID!
  provisioningMode: efs-ap
  directoryPerms: "700"
provisioner: efs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
